[package]
name = "tunneldevice"
version = "0.1.0"
authors = ["Sascha Grunert <mail@saschagrunert.de>"]
build = "build.rs"

[build-dependencies]
bindgen = "0"

[dependencies]
futures = "0"
tokio-core = "0"
